# yml(yaml, 야믈(야멀))
# 시스템 설정에 사용하는 파일
spring:
  datasource:
    driver-class-name: org.postgresql.Driver  #postgresql
#    driver-class-name: com.mysql.cj.jdbc.Driver #mysql
    
    # jdbc - java databse connector
    # :postresql - 데이터베이스 엔진
    # //url - 데이터베이스 주소
    # :5432 - 데이터베이스 접속 포트
    # /postgres - 접속할 데이터베이스
    
    url: jdbc:postgresql://database-1.cgf4d6b8ibcf.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=customer
    # url: jdbc:mysql://database-2.cscsmngkisfl.ap-northeast-2.rds.amazonaws.com:3306/myworkspace
    
    username: postgres  #postgresql
#    username: admin     #mysql

    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true  # create SQL 명령어를 자동으로 수행함, auto-migration
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: amqps://b-f5b27dbc-5576-4d4f-849d-03c019cced61.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!
